import java.io.FileNotFoundException;

class Locations {
  private String locName;
  public weaponsmith weaponsmith;
  public physician physician;

  public Locations() throws FileNotFoundException {
    locName = locationGen();
    weaponsmith = new weaponsmith();
    physician = new physician();
  }

  private String locationGen() { // Sourced from https://www.scifiideas.com/js/city-name-generator.js
    String name = "";
    String[] prefix = {
      "East","High","Low","New","North","Old","South","West", "Los", "Las", "Neo", "San",
    };
    String[] part1 = {
      "Ad",
        "As",
        "At",
        "Atlan",
        "Ant",
        "Ar",
        "Bab","Bac","Back","Bad","Baf","Bag","Bagging",
        "Bai","Bake","Baking","Ban","Bang","Bap","Bar","Barge","Basing",
        "Beef",
        "Bed",
        "Ben",
        "Bic","Bid","Bide","Biden","Big",
        "Bil","Bin","Bip",
        "Black",
        "Black",
        "Blue",
        "Boat",
        "Board",
        "Bog",
        "Bol",
        "Bos",
        "Bop",
        "Bury",
        "Cal",
        "Car",
        "Can",
        "Carol",
        "Cay",
        "Cat",
        "Canal",
        "Char",
        "Chest",
        "Chic","Chick","Chicken",
        "Chig",
        "Claw",
        "Cook",
        "Cor",
        "Col",
        "Cur",
        "Cyber",
        "Dan","Dang","Dark","Davis","Den","Der","Din","Dog","Don","Dong","Dove","Down","Dram",
        "Dun",
        "Dom","Dres","Druk","Duk","East","Em","Ex",
        "Far","Fil","Finn","Fitz","Frank","Full","Fuller","Fynn",
        "Gap",
        "Gar","George",
        "Gel",
        "Gin","Grand","Grave","Gros","Guild",
        "Glyn",
        "Glen",
        "Gop",
        "Ham","Han","Hart",
        "Hel",
        "Hen",
        "Hib","Hic","Hick","High","Hik","Holy","Hor","Horing","Huge","Hugh",
        "In",
        "Ind",
        "Jap",
        "Jip",
        "Jis",
        "Jiz",
        "Ken","Kent",
        "Kit",
        "Kirk",
        "Lar",
        "Lan",
        "Land",
        "Lard",
        "Large","Leah",
        "Lee",
        "Lie",
        "Lin",
        "Lip",
        "Llan",
        "Lland",
        "Llanf",
        "Lon","Long",
        "Lot","Lotta","Low","Luck","Lucky","Luke","Lyon","Mam","Man","Mar","Mat",
        "Mack",
        "Mauve","Mec","Med",
        "Mem",
        "Men",
        "Mel",
        "Mild","Ming","Mom","Mon","Muh","Near","Nord",
        "North",
        "North",
        "Oak",
        "On",
        "Over",
        "Ox",
        "Pat",
        "Pac",
        "Pacific",
        "Pak",
        "Pick",
        "Pop",
        "Pic","Picard","Pip",
        "Pon",
        "Rad","Rap","Raptor","Raven","Ray",
        "Red",
        "Red",
        "Rich","Rock","Rod","Rose","Ros","Rot",
        "Sam",
        "San","Sandle","Scot","Short","South",
        "Shot",
        "St",
        "Stad",
        "Sud","Summer","Sun",
        "Sweet",
        "Swan",
        "Swamp",
        "Tal","Ted","Tep","Tib","Tin","Tip","To","Tor",
        "Under",
        "Val",
        "War",
        "Wat",
        "We","Wel",
        "West",
        "West",
        "Wet",
        "Wharf",
        "White",
        "White",
        "Wil",
        "Win",
        "Winter",
        "Winter",
        "Wolf","Won","Wor","Wu","Xin","Yan","Yen","Zin",
    };
    String[] part2 = {
      "ab","ag","al","an","ay","er","im","in","ing","og",
        "on",
        "or",
        "tic",
        "tor",
        "le",
        "len",
    };
    String[] part3 = {
        "-on-sea",
        "ack", "ago", "al", "aloo", "ama", "ams", "anne", "ant", "anta", "apolis", "ara", "arva", "arvon", "ary",
        "bach", "bat",
        "barton",
        "berg",
        "berg",
        "berge",
        "berj",
        "bord", "borne",
        "bon",
        "bourne",
        "bourne",
        "bourne",
        "borough",
        "boro",
        "bron",
        "bron",
        "burg",
        "burg",
        "borg",
        "boer",
        "brough",
        "burger",
        "burn",
        "burm",
        "burton",
        "burton",
        "bury",
        "bury",
        "by",
        "sby",
        "ca",
        "caster",
        "castle",
        "chester",
        "cestre",
        "cot",
        "cut",
        "click",
        "clirk",
        "dad", "dale", "dam", "dan", "dem", "den", "dena", "dence", "deno", "dense", "dom", "don",
        "dorf",
        "dorn",
        "down",
        "dun", "eau", "enna", "enne", "enya",
        "ertle",
        "esse",
        "est",
        "end",
        "ends",
        "fam",
        "farm",
        "fom", "field", "flow",
        "ford",
        "ford",
        "forn",
        "fornia",
        "fort",
        "fort",
        "fot",
        "foot",
        "fil",
        "furt",
        "furt",
        "fut",
        "gal",
        "gap",
        "gan",
        "gam",
        "gana",
        "gate",
        "gard",
        "gen",
        "gin", "gley", "go",
        "gol",
        "gon",
        "gun",
        "gum",
        "ham",
        "ham",
        "hamm",
        "han",
        "hang", "hard",
        "hole",
        "hom",
        "hon",
        "hong",
        "horn",
        "houn",
        "ia",
        "ica",
        "ian",
        "in",
        "is",
        "ist",
        "ing",
        "ing",
        "inne",
        "ison",
        "istan",
        "kirk",
        "kan",
        "kon",
        "kong",
        "kyo",
        "laix",
        "lan",
        "lan",
        "lane",
        "lane",
        "lin",
        "ling",
        "land",
        "land",
        "lanta",
        "lay",
        "lean",
        "let",
        "lee",
        "ley",
        "ley",
        "lina", "ling", "lock", "lok", "lon", "look",
        "mark",
        "mary",
        "men",
        "mere",
        "mend",
        "mento",
        "moor",
        "moor",
        "moth",
        "mouth",
        "mouth",
        "mum",
        "muth",
        "mund",
        "nan",
        "nell",
        "nes",
        "nett",
        "oaks",
        "oha",
        "oke",
        "olina",
        "oon", "ora", "oria", "otah",
        "otter",
        "on",
        "pen",
        "polis", "poo", "quay", "rell", "river",
        "saw",
        "sburg",
        "sbury", "sen", "sex", "shut", "sing", "skin", "son", "soon", "steak",
        "springs",
        "stein",
        "stein",
        "stan",
        "ston",
        "ston",
        "stone", "stream", "strem",
        "thorpe",
        "tog",
        "ton",
        "ton",
        "tón",
        "tonne",
        "tone",
        "tone",
        "toné",
        "tonne",
        "town",
        "town",
        "tucky",
        "tun",
        "tun",
        "tunne",
        "turn",
        "tuna",
        "tune",
        "uma", "urt",
        "vale",
        "view",
        "view",
        "vile",
        "vile",
        "ville",
        "ville",
        "vis",
        "walk",
        "wanna",
        "ward",
        "ward",
        "wark", "wege", "wei", "werk", "werp",
        "wick",
        "wick",
        "wharf",
        "wood",
        "wood",
        "work",
        "worth",
        "worth",
        "worf",
        "yuan",
        "zhong",
        "hama",
    };
    name += prefix[(int) (Math.random() * prefix.length)];
    name += " ";
    name += part1[(int) (Math.random() * part1.length)];
    name += part2[(int) (Math.random() * part2.length)];
    name += part3[(int) (Math.random() * part3.length)];
    return name;
  }
  public void Starting(){
    
  }
  public String getName(){
    return locName;
  }
}